# The following lines are actual words from captain Haddock, mainly listed from https://fr.wikipedia.org/wiki/Vocabulaire_du_capitaine_Haddock
# original work from Hergé

VOCABULARY = [
    "Accapareur",
    "Aérolithe",
    "Amiral de bateau-lavoir",
    "Amphitron" "Anacoluthe",
    "Analphabète",
    "Analphabète diplômé",
    "Animal",
    "Anthracite",
    "Anthropophage",
    "Anthropopithèque",
    "Apache",
    "Apophtegme",
    "Apprenti-dictateur à la noix de coco",
    "Arlequin",
    "Ascenseur",
    "Astronaute d'eau douce",
    "Athlète complet",
    "Au large !",
    "Autocrate",
    "Autodidacte",
    "Aztèques",
    "Babouin",
    "Bachi-bouzouk",
    "Bachi-bouzouk de tonnerre de Brest",
    "Bachi-bouzouk des Carpathes",
    "Bande de jeunes effrontés",
    "Bande de joyeux drilles",
    "Bande d'ectoplasmes de tonnerre de Brest",
    "Bande d'emplâtres",
    "Bande d'enragés",
    "Bande d'escrocs",
    "Bande d'hurluberlus",
    "Bande de bachi-bouzouks",
    "Bande de brutes",
    "Bande de canaques",
    "Bande de Klu-Klux-Klans",
    "Bande de pirates",
    "Bande de sauvages",
    "Bande de voleurs",
    "Bande de zapotèques de tonnerre de Brest",
    "Bandit",
    "Bayadère de carnaval",
    "Bibelot",
    "Bibendum",
    "Bidule",
    "Blague, fumesterie et compagnie",
    "Boit-sans-soif",
    "Bombe atomique",
    "Bon sang",
    "Bonhomme",
    "Bougre",
    "Bougre d'ectoplasmes à roulettes",
    "Bougre d'ectoplasme de moule à gaufres",
    "Bougre d'amiral de bateau-lavoir",
    "Bougre de crème d'emplâtre à la graisse de hérisson",
    "Bougre d'extrait de cornichon",
    "Bougre d'extrait de crétin des Alpes",
    "Bougre d'extrait d'hydrocarbure",
    "Bougre de faux jeton à la sauce tartare",
    "Bougre de méchant Blanc",
    "Bougre de mouchard",
    "Bougre d'olibrius",
    "Bougre d'ostrogoth",
    "Bougre de papou des Carpathes",
    "Bougre de petit cornichon",
    "Bougre de phénomène de tonnerre de Brest",
    "Bougre de sauvage d'aérolithe de tonnerre de Brest"
    "Bougre de phénomène de moule à gaufres de tonnerre de Brest",
    "Bougre de zouave",
    "Bougre de zouaves d'anthropropithèques",
    "Brigand",
    "Brontosaure",
    "Brute",
    "Bulldozer à réaction",
    "Cachalot",
    "Cake-walk",
    "Calembredaine",
    "Canaille",
    "Canaque",
    "Cannibale",
    "Cannibale emplumé",
    "Capitaine de bateau-lavoir",
    "Casse-pieds",
    "Catachrèse",
    "Cataplasme",
    "Cercopithèque",
    "Cerceuil volant",
    "Chauffard",
    "Chenapan",
    "Cher petit ami",
    "Choléra",
    "Chouette mal empaillée",
    "Chrysanthème",
    "Cigare volant",
    "Cloche à fromage",
    "Cloporte",
    "Clown",
    "Clysopompe",
    "Coléoptère",
    "Coloquinte",
    "Coloquinte à la graisse de hérisson",
    "Concentré de moule à gaufres",
    "Coquin",
    "Cornemuse",
    "Cornichon",
    "Cornichon de zouave à tonerre de Brest" "Cornichon diplômé",
    "Corsaire",
    "Coup de trafalgar",
    "Coupe-jarret",
    "Cow-boy de la route",
    "Crème d'emplâtre à la graisse de hérisson",
    "Crétin de l'Himalaya",
    "Crétin des Alpes",
    "Crétin des Balkans",
    "Commerce noir",
    "Cromagnon",
    "Cuistre",
    "Cyanure",
    "Cyclone",
    "Cyclone ambulant",
    "Cyclotron",
    "Cyrano à quatre pattes",
    "Diable",
    "Diable de --" "Diable de zouave",
    "Diable les emporte",
    "Diable vous étripatouille",
    "Diablesse",
    "Dieu soit loué" "Diplodocus",
    "Doryphore",
    "Doux agneaux",
    "Dynamiteur",
    "Écornifleur",
    "Écraseur",
    "Ectoplasme",
    "Ectoplasme à roulettes",
    "Égoïste",
    "Électron",
    "Emplâtre",
    "Emplâtré à la graisse de hérisson",
    "Empoisonneur",
    "Encordé vous-même",
    "Énergumène",
    "Enfer et damnation",
    "Enfonceur de porte ouverte",
    "Enragé",
    "Épouvantail",
    "Équilibriste",
    "Esclavagiste",
    "Escogriffe",
    "Escroc",
    "Espèce de...",
    "Espèce de loup-garou à la graisse de renoncule de mille sabords",
    "Espèce de porc-épic mal embouché",
    "Entêté",
    "Extrait d'emplâtre",
    "Extrait d'hydrocarbure",
    "Extrait de cornichon",
    "Face de brute",
    "Farceur",
    "Fatma de prisunic",
    "Faux frère",
    "Faux jeton",
    "Faux jeton à la sauce tartare",
    "Fichu --",
    "Fieffé menteur",
    "Fiston",
    "Flibustier",
    "Flibustier de carnaval",
    "Flûte",
    "Forban",
    "Fourbe",
    "Frère de la côte",
    "Froussard",
    "Gaillard",
    "Galopin",
    "Gamin",
    "Gangster",
    "Garde-côtes à la mie de pain",
    "Gargarisme",
    "Garnement",
    "Gibier de potence",
    "Goujat",
    "Graine de vaurien",
    "Graisse de hérisson",
    "Graisse de trombone à coulisse",
    "Grand escogriffe",
    "Grand lâche",
    "Gredin",
    "Grenouille",
    "Gros-plein-de-soupe",
    "Grotesque polichinelle",
    "Gyroscope",
    "Hérétique",
    "Hors-la-loi",
    "Huluberlu",
    "Hydrocarbure",
    "Iconoclaste",
    "Inca de carnaval",
    "Individou de général de tonnerre de Brest",
    "Invertébré",
    "Isotope" "Ivrogne",
    "Jet d'eau ambulant",
    "Jeune chenapan",
    "Jeaune impertinent",
    "Jocrisse",
    "Judas",
    "Jus de réglisse",
    "Khroumir" "KRRTCHMVRTZ",
    "Ku Klux Klan",
    "Kanak",
    "Lâche",
    "Lascar",
    "Lépidoptère",
    "Logarithme",
    "Loup-garou à la graisse de renoncule de mille tonerres de Brest",
    "Maboul",
    "Macaque",
    "Macrocéphale",
    "Malappris",
    "Mahleur",
    "Malheureux",
    "Malotru",
    "Mamelouk",
    "Marchand de guano",
    "Marchand de tapis",
    "Marin d'eau douce",
    "Marmotte mal réveillée",
    "Maudit",
    "Mazette",
    "Mégacycle",
    "Mégalomane",
    "Mercanti",
    "Mercenaire",
    "Mérinos",
    "Mérinos mal peignés",
    "Migou de malheur",
    "Mille milliards de...",
    "Mille milliards de mille millions de mille sabords",
    "Mille milliards de mille sabords",
    "Nille milliards de mille sabords de tonnerre de Brest",
    "Mille milliards de tonnere de Brest",
    "Mille millions de mille milliards de mille sabords",
    "Mille millions de mille milliards de mille sabords de tonnerre de Brest",
    "Mille millions de mille sabords",
    "Mille millions de mille sabords de tonnerre de Brest",
    "Mille millions de sabords",
    "Mille millions de tonnerre de Brest",
    "Mille sabords",
    "Mille tonnerres",
    "Mille tonnerres de Brest",
    "Milliards de...",
    "Misérable",
    "Misérable ectoplasme",
    "Misérable ver de terre",
    "Mitrailleur à bavette",
    "Moratorium",
    "Moricaud",
    "Morues dans un carton à chapaud",
    "Mouchard",
    "Moujik",
    "Moule à gaufres",
    "Moussaillon",
    "Moussaillon de malheur",
    "Mouissaillon du diable",
    "Mufle",
    "MRKRPXZKRMTFRZ",
    "Mussolini de carnaval",
    "Naufrageur",
    "Négrier",
    "Noix de coco",
    "Nom d'une pipe",
    "Nyctalope",
    "Olibrius",
    "Ophicléide",
    "Ornithorynque",
    "Oryctérope",
    "Ostrogoth",
    "Ours mal léché",
    "Pachyderme",
    "Pacte à quatre",
    "Paltoquet",
    "Pantoufle",
    "Papou",
    "Papou des Carpathes",
    "Paranoïaque",
    "Parasites",
    "Patagon",
    "Patagon de zoulou",
    "Patapouf",
    "Patate",
    "Pauvre bougre",
    "Pauvre type",
    "Peau-rouge",
    "Pénultième",
    "Père volant",
    "Péronelle",
    "Perruche bavarde",
    "Perroquet déplumé",
    "Petit choléra",
    "Petit délicat",
    "Petit ornithorynque",
    "Petite tigresse",
    "Petit vaurien",
    "Phénomène",
    "Phlébotome",
    "Phylactère",
    "Phylloxéra",
    "Pignouf",
    "Pirate",
    "Pirate d'eau douce",
    "Pirate du ciel",
    "Plein le dos",
    "Pleurnichard",
    "Polichinelle",
    "Polygraphe",
    "Porc-épic",
    "Potentat",
    "Poussière",
    "Profiteur",
    "Projectile guidé",
    "Protozoaire",
    "Pyromane",
    "Pyrophore",
    "Que diable",
    "Que le grand cric me corque et me fasse avaler ma barbe",
    "Rapace",
    "Rat",
    "Ravachol",
    "Renégat",
    "Rhizopode",
    "Rocaille de tonnerre de Brest",
    "Rocambole",
    "Sacré mitrailleur à bavette",
    "Sacripant",
    "Sajou",
    "Sale bête",
    "Saleté d'appareil à sous",
    "Sale vilaine bête de tonnerre de Brest",
    "Saltimbanque",
    "Sapajou",
    "Sapristi",
    "Satané",
    "Sartrape",
    "Sauvage",
    "Sauvage d'aérolithe",
    "Scélérat",
    "Schizophrène",
    "Scolopendre",
    "Scorpion",
    "Serpent",
    "Simili-martien à la graisse de cabestan",
    "Sinapisme",
    "Sinistre farceur",
    "Sombre brute",
    "Sombre oryctérope",
    "Soulographe",
    "Sous-produit d'ectoplasme",
    "Tas de cornichons",
    "Tas de sauvages",
    "Tchouk-tchouk-nougat",
    "Technocrate",
    "Terroriste",
    "Tête de lard",
    "Tête de mule",
    "Têtu comme une mule",
    "Tigresse",
    "Tonnerre",
    "Tonnerre de Brest",
    "Tonnerre de tonnerre de Brest",
    "Topinambour",
    "Tortionnaire",
    "Trafiquant de chaire humaine",
    "Traîne-potence",
    "Traître",
    "Tricheur",
    "Trgolodyte",
    "Trompe la mort",
    "Troufignol",
    "Vampire",
    "Vandale",
    "Va-nu-pieds",
    "Vaurien",
    "Végétarien",
    "Ver de terre",
    "Vercingétorix de carnaval",
    "Vermicelles",
    "Vermine",
    "Vieille baderne",
    "Vieille branche",
    "Vieille coque rouillée",
    "Vieille marmotte",
    "Vieille perruche bavarde",
    "Vieux farceur",
    "Vieux frère",
    "Vieux rafiot que je suis",
    "Vipère",
    "Vivisectionniste",
    "Volatie de malheur",
    "Voleur",
    "Voleur d'enfants",
    "Wisigoths",
    "Zapotèques",
    "Zèbre",
    "Zigomar",
    "Zouave",
    "Zouave interplanétaire",
    "Zouave à la noix de coco",
    "Zoulou",
]

INSULTS = [
    "Ornithorynque!... Boit-sans-soif!... Bachi-bouzouk!... Anthropophage!... Cercopithèque!... Schizophrène!... Heu... Jocrisse!...",
    "Pignoufs!... Égoïstes!... Moules à gaufres!... Troglodytes!... Polygraphes!...",
    "Macrocéphale!... Amphytrion!... Rocambole!... Ectoplasme!... Phylloxéra!... Cannibal!...",
    "Bougres de faux jetons à la sauce tartare!...",
    "Mille millions de mille sabords de tonnerre de Brest!...",
    "Cornichon!... Pirate!... Espèce de logarithme!... Ectoplsame!... Sapajou!...",
    "Misérable!... Analphabète!... Crétin des alpes!... Je vais te jeter par dessus bord!...",
    "Marin d'eau douce!... Flibustier!... Cornichon!... Logarithme!...",
    "Mille millions de mille milliards de mille sabords de tonnerre de Brest ! C'est de l'eau !",
    "Bandits!... Chauffards!... Saltimbanques!... Ecraseurs!... Brutes!... Nyctalopes!... Parasites!",
    "Mais je ne vous insulte pas, espèce de catachrèse ! Je parlais à un perroquet qui...",
    "Tas de sauvages!... Vampires!... Protozoaires!... Brutes!...",
    "Garnements!... Bandits!... Iconoplastes!...",
    "Brutes!... Canailles!... Lâches!...",
    "Te voilà, espèce de bulldozer à réaction!... Viens donc si tu l'oses, grand escogriffe, et je te transforme en descente de lit",
]
